### PR TITLE
docs: add them

### PR DESCRIPTION
**Pull request by JacobCoffee**
### Pull Request Checklist

- [ ] New code has 100% test coverage
- [x] (If applicable) The prose documentation has been updated to reflect the changes introduced by this PR
- [x] (If applicable) The reference documentation has been updated to reflect the changes introduced by this PR
- [x] Pre-Commit Checks were ran and passed
- [ ] Tests were ran and passed

### Description

- Adds docs in line with the organization branding that can be built upon to reduce service requests in discord and abroad

### Close Issue(s)

-

### CODE REVIEW

**Comment by JacobCoffee** [comment]
@cofin I think for the railway deploy to work we need to do something like https://docs.railway.app/deploy/monorepo#isolated-monorepo mentions? I am not sure why it is failing to get node inside the right layer of the setup.

Maybe @brody192 knows

**Comment by brody192** [comment]
would it be too much trouble to ask you to open a help thread in our discord server? I think tacking this issue would be far easier over there.

**Comment by JacobCoffee** [comment]
ready for review

**Comment by JacobCoffee** [comment]
@cofin hellerrr

**Comment by cofin** [comment]
> @cofin hellerrr

I'll do this review later this afternoon or tomorrow when I'm back in Dallas. Sorry for the delay here.

**Review by cofin — APPROVED** [review]
Thanks man

**Pull request merged**
