### PR TITLE
test: Integration test for /health

### PR DESCRIPTION
**Pull request by FranzForstmayr**
### Pull Request Checklist

- [x] New code has 100% test coverage
- [ ] (If applicable) The prose documentation has been updated to reflect the changes introduced by this PR
- [ ] (If applicable) The reference documentation has been updated to reflect the changes introduced by this PR
- [x] Pre-Commit Checks were ran and passed
- [ ] Tests were ran and passed

### Description
The health API is currently not working due to an msgspec Validation error, as the wrong type is passed. This PR tries to fix this, however it's still WIP, as the tests are not passing yet, although the swagger UI works already.

Maybe someone has hints how to overcome the pytest issues.

### CODE REVIEW

**Comment by FranzForstmayr** [comment]
The issue is now that 

```python
    def provide_queues(self, state: State) -> TaskQueues:
        """Provide the configured job queues.

        Args:
            state: The ``Litestar.state`` instance.

        Returns:
            a ``TaskQueues`` instance.
        """
        return cast("TaskQueues", state.get(self.queues_dependency_key))
```
from
https://github.com/cofin/litestar-saq/blob/27cfd7b79b9d3c35bd19d24cfca8b67cbc30b171/litestar_saq/config.py#L120 

returns `None` but `check_system_health` doesn't accept `None`
```python
async def check_system_health(self, db_session: AsyncSession, task_queues: TaskQueues) -> Response[SystemHealth]:
```

**Comment by Faolain** [comment]
Quick look at this and it seems like this works when running the app live in that provide_queues returns the task_queues upon app state initialization (injected via litestar-saq plugin) but when running the test it returns None?

**Comment by FranzForstmayr** [comment]
This PR requires now the change in https://github.com/cofin/litestar-saq/pull/15 as `provide_queues` should not return None but an empty `TaskQueues` instance (At least according to the return type).

However after changing the URL key in `.env.testing` unrelated tests in tests/unit/lib/test_dependencies start to fail (Event Loop is closed), but only if all tests are executed. When I exucute the unit tests in this file alone everything is fine.

**Comment by cofin** [comment]
> This PR requires now the change in [cofin/litestar-saq#15](https://github.com/cofin/litestar-saq/pull/15) as `provide_queues` should not return None but an empty `TaskQueues` instance (At least according to the return type).
> 
> However after changing the URL key in `.env.testing` unrelated tests in tests/unit/lib/test_dependencies start to fail (Event Loop is closed), but only if all tests are executed. When I exucute the unit tests in this file alone everything is fine.

Thanks for the work on this.  I've merged in your proposed change and made a `v0.1.13` release.

**Review by cofin — APPROVED** [review]

**Comment by FranzForstmayr** [comment]
I've to admit I've no clue what's wrong here.
When the tests are executed manually like `pdm run pytest -k filters` but ``pdm run pytest` fails at the first filter test.

**Pull request merged**
